"""
environment.py — Smart City Traffic Surveillance Analyst
=========================================================
Full OpenEnv-compliant implementation.  Supports openenv-core>=0.2.3 via
try/except shims so the file also works standalone (no pypi package needed
during hackathon Phase-1 unit tests).

Automated-validator contract satisfied:
  - reset()  → returns Observation, clears all internal state
  - step()   → returns Observation with .reward and .done baked in
  - state    → @property returning State (no call parentheses)
  - All models are strict Pydantic v2 subclasses
"""

from __future__ import annotations

import math
import random
import time
from copy import deepcopy
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# openenv-core base classes — graceful fallback when package is absent
# ---------------------------------------------------------------------------
try:
    from openenv.core.models import Action as _Action
    from openenv.core.models import Observation as _Observation
    from openenv.core.models import State as _State
    from openenv.core.environment import Environment as _Environment

    _OPENENV_AVAILABLE = True
except ImportError:
    # Shim: define minimal base classes so all downstream code works without
    # the published package.  This is intentional per hackathon guidance.
    from pydantic import BaseModel

    class _Action(BaseModel):
        metadata: Dict[str, Any] = {}

    class _Observation(BaseModel):
        done: bool = False
        reward: float = 0.0
        metadata: Dict[str, Any] = {}

    class _State(BaseModel):
        step_count: int = 0

    class _Environment:
        pass

    _OPENENV_AVAILABLE = False

from pydantic import BaseModel, Field, model_validator

# ===========================================================================
# Section 1 — Pydantic Data Models
# ===========================================================================

class VehicleTelemetry(BaseModel):
    """Single vehicle data point in one camera frame."""

    vehicle_id: str = Field(..., description="Unique vehicle identifier, e.g. 'V001'")
    bbox: Tuple[float, float, float, float] = Field(
        ..., description="Bounding box (x1, y1, x2, y2) in pixel space"
    )
    speed_kmh: float = Field(..., ge=0.0, description="Speed in km/h")
    coordinates: Tuple[float, float] = Field(
        ..., description="GPS (lat, lon) centroid of the bounding box"
    )
    heading_deg: float = Field(
        default=0.0, description="Vehicle heading in degrees (0=North, 90=East)"
    )


class Alert(BaseModel):
    """An active alert generated by the environment or the agent."""

    alert_id: str
    alert_type: str  # 'collision' | 'near_miss' | 'ems_dispatched' | 'sign_updated'
    frame_id: Optional[int] = None
    vehicle_ids: List[str] = []
    coordinates: Optional[Tuple[float, float]] = None
    details: Dict[str, Any] = {}
    timestamp: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# Observation
# ---------------------------------------------------------------------------
class TrafficObservation(_Observation):
    """
    Observation returned after every reset() and step().

    Fields that satisfy the automated validator:
      - done   (inherited from _Observation)
      - reward (inherited from _Observation)
      - current_frame, telemetry_data, active_alerts (domain-specific)
    """

    current_frame: int = Field(default=0, description="0-indexed current frame number")
    total_frames: int = Field(default=30, description="Total frames in the episode")
    telemetry_data: List[VehicleTelemetry] = Field(
        default_factory=list,
        description="All vehicle telemetry records visible in current_frame",
    )
    active_alerts: List[Alert] = Field(
        default_factory=list,
        description="All alerts currently active (tagged or dispatched)",
    )
    episode_id: Optional[str] = None
    task_name: Optional[str] = None
    # Inherited: done: bool = False, reward: float = 0.0


# ---------------------------------------------------------------------------
# Action
# ---------------------------------------------------------------------------
VALID_ACTIONS = {"tag_collision", "tag_near_miss", "dispatch_ems", "update_signs", "advance_frame", "noop"}

class TrafficAction(_Action):
    """
    Polymorphic action the agent can submit.

    action_type values:
      • tag_collision    — mark a collision event
      • tag_near_miss    — mark a near-miss event
      • dispatch_ems     — send ambulance/fire to coordinates
      • update_signs     — change upstream VMS sign messages
      • advance_frame    — move to the next camera frame (no side effect)
      • noop             — do nothing (penalised mildly)

    payload keys vary by action_type:
      tag_collision  : {frame_id: int, vehicle_ids: List[str]}
      tag_near_miss  : {vehicle_ids: List[str], minimum_distance: float}
      dispatch_ems   : {coordinates: [lat, lon], service_type: str}
      update_signs   : {sign_ids: List[str], message: str, upstream: bool}
      advance_frame  : {}
      noop           : {}
    """

    action_type: str = Field(..., description=f"One of {VALID_ACTIONS}")
    payload: Dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_action_type(self) -> "TrafficAction":
        if self.action_type not in VALID_ACTIONS:
            raise ValueError(
                f"action_type '{self.action_type}' is not valid. "
                f"Must be one of {VALID_ACTIONS}"
            )
        return self


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------
class TrafficState(_State):
    """
    Internal state snapshot exposed via env.state property.

    Satisfies validator: step_count (inherited), plus domain fields.
    """

    task_name: Optional[str] = None
    episode_id: Optional[str] = None
    current_frame: int = 0
    total_frames: int = 30
    cumulative_reward: float = 0.0
    last_action: Optional[Dict[str, Any]] = None
    tagged_collisions: List[Dict[str, Any]] = []
    tagged_near_misses: List[Dict[str, Any]] = []
    dispatched_ems: List[Dict[str, Any]] = []
    updated_signs: List[Dict[str, Any]] = []
    active_alerts: List[Dict[str, Any]] = []
    # Ground-truth (set once per episode via reset)
    ground_truth: Dict[str, Any] = {}
    episode_done: bool = False
    # Inherited: step_count: int = 0


# ===========================================================================
# Section 2 — Scenario Generator
# ===========================================================================

def _haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Return distance in metres between two GPS points."""
    R = 6_371_000.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlam / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def _bbox_overlap(b1: Tuple, b2: Tuple) -> bool:
    """Return True if two bounding boxes overlap."""
    return not (b1[2] < b2[0] or b2[2] < b1[0] or b1[3] < b2[1] or b2[3] < b1[1])


class ScenarioGenerator:
    """
    Generates reproducible multi-frame traffic scenarios including:
      - normal traffic flow
      - a hidden collision event at a randomised frame
      - a near-miss trajectory
    """

    BASE_LAT = 37.7749   # San Francisco
    BASE_LON = -122.4194

    def __init__(self, rng: random.Random):
        self.rng = rng

    def _random_gps(self, spread: float = 0.005) -> Tuple[float, float]:
        return (
            self.BASE_LAT + self.rng.uniform(-spread, spread),
            self.BASE_LON + self.rng.uniform(-spread, spread),
        )

    def _vehicle_id(self, n: int) -> str:
        return f"V{n:03d}"

    def generate_episode(
        self,
        total_frames: int = 30,
        n_vehicles: int = 6,
        collision_frame: Optional[int] = None,
    ) -> Dict[str, Any]:
        """
        Returns a full episode dict with:
          - frames: List[List[VehicleTelemetry]]
          - ground_truth: {collision_frame, collision_vehicles, near_miss_vehicle, min_distance, ...}
        """
        if collision_frame is None:
            collision_frame = self.rng.randint(5, total_frames - 5)

        # Assign stable base positions and headings to each vehicle
        vehicle_configs = []
        for i in range(1, n_vehicles + 1):
            lat, lon = self._random_gps()
            speed = self.rng.uniform(30, 90)
            heading = self.rng.uniform(0, 360)
            vehicle_configs.append(
                {"id": self._vehicle_id(i), "lat": lat, "lon": lon, "speed": speed, "heading": heading}
            )

        # Identify collision pair and near-miss vehicle
        coll_v1_idx, coll_v2_idx = 0, 1
        near_miss_idx = 2

        # Near-miss: vehicle 3 drifts close to vehicle 4 around frame 15
        near_miss_frame = collision_frame - 5 if collision_frame > 10 else collision_frame + 5
        near_miss_min_dist = round(self.rng.uniform(3.5, 8.0), 2)  # metres

        frames: List[List[Dict]] = []

        for f in range(total_frames):
            frame_vehicles: List[Dict] = []
            for cfg in vehicle_configs:
                vid = cfg["id"]
                # Normal progression: advance lat/lon by speed
                progress = f * 0.00001 * cfg["speed"] / 50
                lat = cfg["lat"] + progress * math.cos(math.radians(cfg["heading"]))
                lon = cfg["lon"] + progress * math.sin(math.radians(cfg["heading"]))
                speed = cfg["speed"]

                # Simulate collision: V001 and V002 converge and stop at collision_frame
                if vid in (
                    vehicle_configs[coll_v1_idx]["id"],
                    vehicle_configs[coll_v2_idx]["id"],
                ):
                    if f < collision_frame:
                        # Approach phase
                        frac = f / collision_frame
                        target_lat = (
                            vehicle_configs[coll_v1_idx]["lat"]
                            + vehicle_configs[coll_v2_idx]["lat"]
                        ) / 2
                        target_lon = (
                            vehicle_configs[coll_v1_idx]["lon"]
                            + vehicle_configs[coll_v2_idx]["lon"]
                        ) / 2
                        lat = cfg["lat"] + frac * (target_lat - cfg["lat"])
                        lon = cfg["lon"] + frac * (target_lon - cfg["lon"])
                    elif f == collision_frame:
                        # IMPACT: both at same point, speed drops to 0
                        lat = (
                            vehicle_configs[coll_v1_idx]["lat"]
                            + vehicle_configs[coll_v2_idx]["lat"]
                        ) / 2
                        lon = (
                            vehicle_configs[coll_v1_idx]["lon"]
                            + vehicle_configs[coll_v2_idx]["lon"]
                        ) / 2
                        speed = 0.0
                    else:
                        # Post-collision: stationary
                        lat = (
                            vehicle_configs[coll_v1_idx]["lat"]
                            + vehicle_configs[coll_v2_idx]["lat"]
                        ) / 2
                        lon = (
                            vehicle_configs[coll_v1_idx]["lon"]
                            + vehicle_configs[coll_v2_idx]["lon"]
                        ) / 2
                        speed = 0.0

                # Near miss adjustment for vehicle[near_miss_idx]
                if vid == vehicle_configs[near_miss_idx]["id"]:
                    anchor_v = vehicle_configs[near_miss_idx + 1]
                    if f == near_miss_frame:
                        # Temporarily bring within near_miss_min_dist
                        offset_lat = near_miss_min_dist / 111_000
                        lat = anchor_v["lat"] + offset_lat
                        lon = anchor_v["lon"]
                        speed = self.rng.uniform(15, 30)

                # Build bbox around GPS point (pixel proxy: scale gps diff to pixels)
                px = (lon - self.BASE_LON) * 100_000
                py = (lat - self.BASE_LAT) * 100_000
                w, h = 40.0, 20.0
                bbox = (px - w / 2, py - h / 2, px + w / 2, py + h / 2)

                frame_vehicles.append({
                    "vehicle_id": vid,
                    "bbox": bbox,
                    "speed_kmh": round(speed, 2),
                    "coordinates": (round(lat, 7), round(lon, 7)),
                    "heading_deg": round(cfg["heading"], 2),
                })

            frames.append(frame_vehicles)

        # Compute actual collision GPS
        collision_lat = (
            vehicle_configs[coll_v1_idx]["lat"] + vehicle_configs[coll_v2_idx]["lat"]
        ) / 2
        collision_lon = (
            vehicle_configs[coll_v1_idx]["lon"] + vehicle_configs[coll_v2_idx]["lon"]
        ) / 2

        # Compute near-miss: anchor vehicle position at near_miss_frame
        anchor = vehicle_configs[near_miss_idx + 1]
        nm_v = vehicle_configs[near_miss_idx]
        anchor_lat = anchor["lat"]
        anchor_lon = anchor["lon"]
        offset_lat = near_miss_min_dist / 111_000
        nm_lat = anchor_lat + offset_lat
        nm_lon = anchor_lon
        actual_dist = round(
            _haversine_m(nm_lat, nm_lon, anchor_lat, anchor_lon), 2
        )

        ground_truth = {
            "collision_frame": collision_frame,
            "collision_vehicle_ids": [
                vehicle_configs[coll_v1_idx]["id"],
                vehicle_configs[coll_v2_idx]["id"],
            ],
            "collision_coordinates": (round(collision_lat, 7), round(collision_lon, 7)),
            "near_miss_vehicle_id": vehicle_configs[near_miss_idx]["id"],
            "near_miss_anchor_vehicle_id": vehicle_configs[near_miss_idx + 1]["id"],
            "near_miss_frame": near_miss_frame,
            "near_miss_min_distance_m": actual_dist,
            "sign_ids": ["SIGN_N1", "SIGN_N2"],  # Upstream signs to update
        }

        return {"frames": frames, "ground_truth": ground_truth, "total_frames": total_frames}


# ===========================================================================
# Section 3 — Reward Engine
# ===========================================================================

class RewardEngine:
    """
    Computes dense, continuous reward signals (never purely sparse).

    Reward philosophy:
      +1.0  — perfect action (right type, right payload, right sequence)
      +0.5  — partial credit (right type, mostly right payload)
      -0.1  — non-destructive wrong action (noop, wrong frame)
      -0.3  — hallucinated vehicle IDs that don't exist in the episode
      -0.5  — repeat action already submitted correctly
    """

    def __init__(self, ground_truth: Dict[str, Any], all_vehicle_ids: List[str]):
        self.gt = ground_truth
        self.all_vehicle_ids = set(all_vehicle_ids)
        self._collision_tagged = False
        self._ems_dispatched = False
        self._signs_updated = False

    def score(self, action: TrafficAction, state: TrafficState) -> float:
        at = action.action_type
        p = action.payload

        if at == "noop":
            return -0.05  # mild penalty for doing nothing

        if at == "advance_frame":
            return 0.0  # neutral

        # Check for hallucinated vehicle IDs
        submitted_ids: List[str] = p.get("vehicle_ids", [])
        hall = [v for v in submitted_ids if v not in self.all_vehicle_ids]
        if hall:
            return -0.3  # hallucination penalty

        if at == "tag_collision":
            if self._collision_tagged:
                return -0.5  # duplicate
            submitted_frame = p.get("frame_id")
            submitted_vids = set(p.get("vehicle_ids", []))
            gt_frame = self.gt["collision_frame"]
            gt_vids = set(self.gt["collision_vehicle_ids"])

            frame_ok = submitted_frame == gt_frame
            vids_ok = submitted_vids == gt_vids

            if frame_ok and vids_ok:
                self._collision_tagged = True
                return 1.0
            elif frame_ok or vids_ok:
                return 0.5  # partial credit
            else:
                return -0.1

        if at == "tag_near_miss":
            submitted_vids = set(p.get("vehicle_ids", []))
            submitted_dist = p.get("minimum_distance", None)
            gt_vid = self.gt["near_miss_vehicle_id"]
            gt_dist = self.gt["near_miss_min_distance_m"]

            vid_ok = gt_vid in submitted_vids
            dist_ok = (
                submitted_dist is not None
                and abs(submitted_dist - gt_dist) <= 1.5  # 1.5m tolerance
            )
            if vid_ok and dist_ok:
                return 1.0
            elif vid_ok:
                return 0.4
            else:
                return -0.1

        if at == "dispatch_ems":
            if self._ems_dispatched:
                return -0.5
            coords = p.get("coordinates", [])
            if len(coords) != 2:
                return -0.1
            gt_lat, gt_lon = self.gt["collision_coordinates"]
            dist_m = _haversine_m(coords[0], coords[1], gt_lat, gt_lon)
            service = p.get("service_type", "")

            coord_ok = dist_m < 200  # within 200 m
            service_ok = service in ("ambulance", "fire", "police", "ems")

            if coord_ok and service_ok:
                self._ems_dispatched = True
                return 1.0
            elif coord_ok:
                return 0.5
            else:
                return -0.1

        if at == "update_signs":
            if self._signs_updated:
                return -0.5
            sign_ids = set(p.get("sign_ids", []))
            gt_signs = set(self.gt["sign_ids"])
            message = p.get("message", "")
            upstream = p.get("upstream", False)

            sign_ok = bool(sign_ids & gt_signs)  # at least one correct sign
            msg_ok = len(message) > 3  # non-empty reasonable message
            up_ok = upstream is True

            if sign_ok and msg_ok and up_ok:
                self._signs_updated = True
                return 1.0
            elif sign_ok and msg_ok:
                return 0.5
            elif msg_ok:
                return 0.2
            else:
                return -0.1

        return -0.1  # unknown action type fallback


# ===========================================================================
# Section 4 — Core Environment
# ===========================================================================

class TrafficSurveillanceEnv(_Environment):
    """
    Smart City Traffic Surveillance Analyst — OpenEnv Environment.

    Episode lifecycle:
      1. reset(task_name=...) → generates a fresh scenario, returns obs
      2. Agent calls step(action) repeatedly (advance_frame + tag/dispatch)
      3. Episode ends when agent completes required actions or max_steps hit

    Validator contract:
      ✓ reset() returns TrafficObservation
      ✓ step()  returns TrafficObservation with .reward and .done
      ✓ state   is a @property returning TrafficState
    """

    MAX_STEPS_PER_EPISODE = 60

    def __init__(self):
        self._state: TrafficState = TrafficState()
        self._scenario: Dict[str, Any] = {}
        self._reward_engine: Optional[RewardEngine] = None
        self._rng = random.Random()

    # ------------------------------------------------------------------
    # reset()
    # ------------------------------------------------------------------
    def reset(
        self,
        seed: Optional[int] = None,
        episode_id: Optional[str] = None,
        task_name: Optional[str] = None,
        **kwargs: Any,
    ) -> TrafficObservation:
        """
        Reset the environment to a clean initial state.

        Args:
            seed:       RNG seed for reproducibility.
            episode_id: Optional identifier for this episode.
            task_name:  One of 'collision_tagging', 'near_miss_detection',
                        'active_incident_management'. Defaults to 'collision_tagging'.

        Returns:
            TrafficObservation at frame 0.
        """
        # Deterministic seed
        if seed is not None:
            self._rng = random.Random(seed)
        else:
            self._rng = random.Random()

        task_name = task_name or "collision_tagging"
        ep_id = episode_id or f"ep_{int(time.time())}"

        # Generate scenario
        gen = ScenarioGenerator(self._rng)
        self._scenario = gen.generate_episode(total_frames=30, n_vehicles=6)
        gt = self._scenario["ground_truth"]

        # All vehicle IDs in this episode
        all_vids = list({
            v["vehicle_id"]
            for frame in self._scenario["frames"]
            for v in frame
        })

        # Fresh reward engine
        self._reward_engine = RewardEngine(ground_truth=gt, all_vehicle_ids=all_vids)

        # Clean state
        self._state = TrafficState(
            step_count=0,
            task_name=task_name,
            episode_id=ep_id,
            current_frame=0,
            total_frames=self._scenario["total_frames"],
            cumulative_reward=0.0,
            last_action=None,
            tagged_collisions=[],
            tagged_near_misses=[],
            dispatched_ems=[],
            updated_signs=[],
            active_alerts=[],
            ground_truth=gt,
            episode_done=False,
        )

        return self._build_observation(reward=0.0, done=False)

    # ------------------------------------------------------------------
    # step()
    # ------------------------------------------------------------------
    def step(
        self,
        action: TrafficAction,
        timeout_s: Optional[float] = None,
        **kwargs: Any,
    ) -> TrafficObservation:
        """
        Apply an action and advance the environment.

        Returns TrafficObservation with .reward (dense signal) and .done.
        """
        if self._reward_engine is None:
            raise RuntimeError("Call reset() before step().")

        self._state.step_count += 1
        self._state.last_action = action.model_dump()

        # ------------------------------------------------------------------
        # Compute reward
        # ------------------------------------------------------------------
        reward = self._reward_engine.score(action, self._state)
        self._state.cumulative_reward += reward

        # ------------------------------------------------------------------
        # Apply side effects of action
        # ------------------------------------------------------------------
        at = action.action_type
        p = action.payload

        if at == "advance_frame":
            if self._state.current_frame < self._state.total_frames - 1:
                self._state.current_frame += 1

        elif at == "tag_collision":
            alert = Alert(
                alert_id=f"COLL_{self._state.step_count}",
                alert_type="collision",
                frame_id=p.get("frame_id"),
                vehicle_ids=p.get("vehicle_ids", []),
                coordinates=self._state.ground_truth.get("collision_coordinates"),
            )
            self._state.tagged_collisions.append(alert.model_dump())
            self._state.active_alerts.append(alert.model_dump())

        elif at == "tag_near_miss":
            alert = Alert(
                alert_id=f"NM_{self._state.step_count}",
                alert_type="near_miss",
                vehicle_ids=p.get("vehicle_ids", []),
                details={"minimum_distance": p.get("minimum_distance")},
            )
            self._state.tagged_near_misses.append(alert.model_dump())
            self._state.active_alerts.append(alert.model_dump())

        elif at == "dispatch_ems":
            alert = Alert(
                alert_id=f"EMS_{self._state.step_count}",
                alert_type="ems_dispatched",
                coordinates=tuple(p.get("coordinates", [0.0, 0.0])),
                details={"service_type": p.get("service_type", "ambulance")},
            )
            self._state.dispatched_ems.append(alert.model_dump())
            self._state.active_alerts.append(alert.model_dump())

        elif at == "update_signs":
            alert = Alert(
                alert_id=f"SIGN_{self._state.step_count}",
                alert_type="sign_updated",
                details={
                    "sign_ids": p.get("sign_ids", []),
                    "message": p.get("message", ""),
                    "upstream": p.get("upstream", False),
                },
            )
            self._state.updated_signs.append(alert.model_dump())
            self._state.active_alerts.append(alert.model_dump())

        # ------------------------------------------------------------------
        # Check episode termination
        # ------------------------------------------------------------------
        done = self._check_done()
        self._state.episode_done = done

        return self._build_observation(reward=reward, done=done)

    # ------------------------------------------------------------------
    # state (property)
    # ------------------------------------------------------------------
    @property
    def state(self) -> TrafficState:
        """Return current internal state snapshot. No parentheses needed."""
        return deepcopy(self._state)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _build_observation(self, reward: float, done: bool) -> TrafficObservation:
        """Construct observation from current state."""
        frame_idx = self._state.current_frame
        raw_frame = self._scenario.get("frames", [[]])[frame_idx] if self._scenario else []

        telemetry = [VehicleTelemetry(**v) for v in raw_frame]
        alerts = [Alert(**a) for a in self._state.active_alerts]

        return TrafficObservation(
            done=done,
            reward=reward,
            current_frame=frame_idx,
            total_frames=self._state.total_frames,
            telemetry_data=telemetry,
            active_alerts=alerts,
            episode_id=self._state.episode_id,
            task_name=self._state.task_name,
        )

    def _check_done(self) -> bool:
        """
        Episode is done when:
          - Max steps exceeded, OR
          - For active_incident_management: all 3 sub-tasks completed, OR
          - The frame pointer reaches the end AND the task-specific condition is met
        """
        if self._state.step_count >= self.MAX_STEPS_PER_EPISODE:
            return True

        task = self._state.task_name
        if task == "collision_tagging":
            return len(self._state.tagged_collisions) > 0
        elif task == "near_miss_detection":
            return len(self._state.tagged_near_misses) > 0
        elif task == "active_incident_management":
            return (
                len(self._state.tagged_collisions) > 0
                and len(self._state.dispatched_ems) > 0
                and len(self._state.updated_signs) > 0
            )
        return False

    def get_all_vehicle_ids(self) -> List[str]:
        """Utility: return all vehicle IDs present in this episode."""
        if not self._scenario:
            return []
        return list({
            v["vehicle_id"]
            for frame in self._scenario["frames"]
            for v in frame
        })

    def get_frame(self, frame_idx: int) -> List[Dict]:
        """Return raw telemetry dict list for a specific frame."""
        if not self._scenario or frame_idx >= len(self._scenario["frames"]):
            return []
        return self._scenario["frames"][frame_idx]

    def get_ground_truth(self) -> Dict[str, Any]:
        """Expose ground truth (for graders — do NOT expose to agent)."""
        return deepcopy(self._scenario.get("ground_truth", {}))


# ---------------------------------------------------------------------------
# Module-level factory function — used by openenv-core server bootstrap
# ---------------------------------------------------------------------------
def make_env(**kwargs) -> TrafficSurveillanceEnv:
    """Factory function required by openenv-core create_fastapi_app()."""
    return TrafficSurveillanceEnv()
